config/routes.rb
Rails.application.routes.draw do
  get 'toppages/index'
  root to: 'toppages#index'
  
  resources :articles do
    resource :favorites, only: [:create, :destroy, :update, :edit]
    resources :comments
    member do
      patch :release
      patch :nonrelease
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    favorite = current_user.favorites.build(article_id: params[:article_id])
    favorite.save
    redirect_to articles_path
  end

  def destroy
    favorite = Favorite.find_by(article_id: params[:article_id], user_id: current_user.id)
    favorite.destroy
    redirect_to articles_path
  end
end

app/views/favorites/_favorite_button.html.erb
<% articles.each do |article| %>
  <div class="post-list">
    <h6><%= article.article.name %></h6>
    <%= link_to "投稿者:" + article.article.user.name, user_path(article.article.user) %><br>
    作成日:<%= article.article.created_at.strftime("%Y年%m月%d日") %><br>
    タグ:<% article.article.tag_list.each do |tag| %>
      <%=link_to tag, articles_path(tag_name: tag), class: "tag"%>
    <% end %><br>
    <%= link_to '', article_path %>
    <% if current_user == article.user %>
    <%= link_to '更新', edit_article_path(article), class: 'link-btn' %>
    <%= link_to '削除', article_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link-btn' %>
    <% end %>
    <% if article.article.favorited_by?(current_user) %>
        <%=link_to 'お気に入り解除', article_favorites_path(article.id), method: :delete, class: 'anlike-btn' %>
    <% else %>
        <%=link_to 'お気に入り', article_favorites_path(article.id), method: :post, class: 'link-btn' %>
    <% end %>
  </div>
<% end %>