config/routes.rb
Rails.application.routes.draw do
  get 'toppages/index'
  root to: 'toppages#index'
  
  resources :articles do
    resource :favorites, only: [:create, :destroy, :update, :edit]
    resources :comments
    member do
      patch :release
      patch :nonrelease
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ProfileUploader
  
  validates :name, presence: true, length: { maximum: 25 }
  validates :introduction, presence: true, length: { maximum: 200 }          
  has_secure_password
  
  has_many :articles
  has_many :comments
  
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :reverses_of_relationship, dependent: :destroy
  
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  has_many :favorites
  has_many :favorites, dependent: :destroy
  
  
  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      User.where(['name LIKE ? OR introduction LIKE ?', "%#{search}%", "%#{search}%"])
    else
      User.all #全て表示。
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :destroy, :likes, :edit, :update
  ]
  
  def index
    @users = User.search(params[:search]).page(params[:page]).per(50)
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.order(id: :desc).page(params[:page]).per(15)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    flash[:success] = '退会しました!!'
    redirect_to articles_path
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'ユーザ情報を変更しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザ情報の更新に失敗しました。'
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.favorites.page(params[:page])
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_profile.html.erb
<% if  @user.image? %>
  <%= image_tag @user.image.thumb.url, alt: @user.name + "のアイコン" %>
<% else %>
  <%= content_tag :div, image_tag("アイコン.jpeg")%>
<% end %>
<%= @user.name %><%= render 'relationships/follow_button', user: @user %>
<p><%= simple_format(@user.introduction, class: "longtext") %></p>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="">
    <% users.each do |user| %>
      <li class="">
        <% if  user.image? %>
          <%= image_tag user.image.thumb.url, alt: user.name + "のアイコン" %>
        <% else %>
          <%= content_tag :div, image_tag("アイコン.jpeg")%>
        <% end %>
        <div class="">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'プロフィール', user_path(user),class: "link-btn" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="">
  <h1>プロフィール編集</h1>
  <p>必要な箇所のみ入力し、変更ボタンを押してください</p>
</div>

<div class="">
  <div class="">

    <%= form_with(model: @user, local: true) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-set">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-field' %>
      </div>

      <div class="form-set">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-field' %>
      </div>

      <div class="form-set">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-field' %>
      </div>
      
      <div class="form-set">
        <%= f.label :profile_image, 'プロフィール画像' %>
        <%= f.file_field :image, class: '' %>
      </div>
      
      <div class="form-set">
        <%= f.label :introduction, 'プロフィール' %>
        <%= f.text_area :introduction, class: 'form-field' %>
      </div>

      <%= f.submit '変更', class: 'form-btn' %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="">
  <%= render 'user_profile' %>
</div>
<div class="">
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿済み<span class="tag"><%= @count_articles %></span></a></li>
    <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中<span class="tag"><%= @count_followings %></span></a></li>
    <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="tag"><%= @count_followers %></span></a></li>
    <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="tag"><%= @count_likes %></span></a></li>
  </ul>
  <%= render 'users', users: @followers %>
  <%= paginate @followers %>
</div>

app/views/users/followings.html.erb
<div class="">
  <%= render 'user_profile' %>
</div>
<div class="list back">
    <ul class="nav nav-tabs nav-justified">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿済み<span class="tag"><%= @count_articles %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中<span class="tag"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="tag"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="tag"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
    <%= paginate @followings %>
  </div>
</div>

app/views/users/index.html.erb
<div class="search-form">
  <%= form_tag users_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], placeholder:"ユーザー名、プロフィール" %>
      <%= submit_tag "ユーザーの検索" %>
  <% end %>
</div>

<%= render 'users', users: @users %>
<div><%= paginate @users %></div>

app/views/users/likes.html.erb
<div class="">
  <%= render 'user_profile' %>
</div>
<div class="list back">
    <ul class="nav nav-tabs nav-justified">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿済み<span class="tag"><%= @count_articles %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中<span class="tag"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="tag"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="tag"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'favorites/favorite_button', articles: @likes %>
    <%= paginate @likes %>
  </div>
</div>

app/views/users/new.html.erb
<div class="">
  <h1>ユーザー作成</h1>
  <p>画像以外は全て入力してください</p>
</div>

<div class="">
  <div class="">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-set">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-field' %>
      </div>
      
      <div class="form-set">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-field' %>
      </div>

      <div class="form-set">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-field' %>
      </div>
      
      <div class=form-set"">
        <%= f.label :profile_image, 'プロフィール画像' %>
        <%= f.file_field :image, class: '' %>
      </div>
      
      <div class="form-set">
        <%= f.label :introduction, 'プロフィール' %>
        <%= f.text_area :introduction, class: 'form-field' %>
      </div>

      <%= f.submit '入会', class: 'form-btn' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="">
  <%= render 'user_profile' %>
</div>
<div class="">
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿済み<span class="tag"><%= @count_articles %></span></a></li>
    <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中<span class="tag"><%= @count_followings %></span></a></li>
    <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="tag"><%= @count_followers %></span></a></li>
    <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="tag"><%= @count_likes %></span></a></li>
  </ul>
    <% @articles.each do |article| %>
      <div class="post-list">
        <h6><%= article.name %></h6>
        <div>
          <%= link_to "投稿者:" + article.user.name, user_path(article.user) %><br>
          作成日:<%= article.created_at.strftime("%Y年%m月%d日") %>
        </div>
        タグ:<% article.tag_list.each do |tag| %>
          <%=link_to tag, articles_path(tag_name: tag), class: "tag"%>
        <% end %><br>
        <%= link_to '閲覧', article, class: 'link-btn' %>
        <% if current_user == article.user %>
          <%= link_to '更新', edit_article_path(article), class: 'link-btn' %>
          <%= link_to '削除', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link-btn' %>
        <% end %>
        <% if article.favorited_by?(current_user) %>
            <%=link_to 'お気に入り解除', article_favorites_path(article.id), method: :delete, class: 'anlike-btn' %>
        <% else %>
            <%=link_to 'お気に入り', article_favorites_path(article.id), method: :post, class: 'link-btn' %>
        <% end %>
      </div>
    <% end %>
    <%= paginate @articles %>
</div>